// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: skiff/registry/v1alpha1/registry.proto

package v1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
// buf:lint:ignore ENUM_VALUE_PREFIX
// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type Field_Type int32

const (
	Field_string Field_Type = 0
	Field_bool   Field_Type = 1
	Field_number Field_Type = 2
	Field_array  Field_Type = 3
)

// Enum value maps for Field_Type.
var (
	Field_Type_name = map[int32]string{
		0: "string",
		1: "bool",
		2: "number",
		3: "array",
	}
	Field_Type_value = map[string]int32{
		"string": 0,
		"bool":   1,
		"number": 2,
		"array":  3,
	}
)

func (x Field_Type) Enum() *Field_Type {
	p := new(Field_Type)
	*p = x
	return p
}

func (x Field_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_skiff_registry_v1alpha1_registry_proto_enumTypes[0].Descriptor()
}

func (Field_Type) Type() protoreflect.EnumType {
	return &file_skiff_registry_v1alpha1_registry_proto_enumTypes[0]
}

func (x Field_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field_Type.Descriptor instead.
func (Field_Type) EnumDescriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{3, 0}
}

// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
// buf:lint:ignore ENUM_VALUE_PREFIX
// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type File_Type int32

const (
	File_plain    File_Type = 0
	File_template File_Type = 1
	File_plugin   File_Type = 2
)

// Enum value maps for File_Type.
var (
	File_Type_name = map[int32]string{
		0: "plain",
		1: "template",
		2: "plugin",
	}
	File_Type_value = map[string]int32{
		"plain":    0,
		"template": 1,
		"plugin":   2,
	}
)

func (x File_Type) Enum() *File_Type {
	p := new(File_Type)
	*p = x
	return p
}

func (x File_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (File_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_skiff_registry_v1alpha1_registry_proto_enumTypes[1].Descriptor()
}

func (File_Type) Type() protoreflect.EnumType {
	return &file_skiff_registry_v1alpha1_registry_proto_enumTypes[1]
}

func (x File_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use File_Type.Descriptor instead.
func (File_Type) EnumDescriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{4, 0}
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Packages      []*Package             `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Registry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Registry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Registry) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

type Package struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the package. This should be unique between all packages within a registry.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A short description of the purpose of this package and what it contains. Should be LLM-friendly. Supports markdown.
	Description string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Files       []*File `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	// If a field does not have a default, it is marked as required.
	Schema        *Schema `protobuf:"bytes,4,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Package) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Package) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Field               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Schema) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the field. This must be unique between all fields.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The expected type of the field.
	Type *Field_Type `protobuf:"varint,2,opt,name=type,proto3,enum=skiff.registry.v1alpha1.Field_Type,oneof" json:"type,omitempty"`
	// If the type is set to "array", this specifies the underlying type. Required if type is "array".
	Items *Field_SubField `protobuf:"bytes,3,opt,name=items,proto3,oneof" json:"items,omitempty"`
	// A short description of the field. This is highly recommended to provide context to all consumers of your package.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// The default value. If set, the field will be marked as optional. If the enum field is set, this field must be one of the enum values.
	Default *structpb.Value `protobuf:"bytes,5,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Restrict your options to a set of values to choose.
	Enum          *structpb.ListValue `protobuf:"bytes,6,opt,name=enum,proto3,oneof" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() Field_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Field_string
}

func (x *Field) GetItems() *Field_SubField {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Field) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Field) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Field) GetEnum() *structpb.ListValue {
	if x != nil {
		return x.Enum
	}
	return nil
}

type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path to the template relative to the root of the registry. The root of the registry is the directory housing your 'registry.json' file. Cannot be outside of the registry root.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The target path of the rendered template relative to the root of the project. Accepts template parameters.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// The raw contents of the file. You do not need to populate this manually. This field is set if the data is binary. It is mutually exclusive with the content field.
	Raw []byte `protobuf:"bytes,3,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	// The type of the file.
	Type File_Type `protobuf:"varint,4,opt,name=type,proto3,enum=skiff.registry.v1alpha1.File_Type" json:"type,omitempty"`
	// The text contents of the file. This field will be populated if the file contains valid UTF-8 text. Otherwise, the contents are set in the raw field. You do not need to populate this manually.
	Content       *string `protobuf:"bytes,5,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *File) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *File) GetType() File_Type {
	if x != nil {
		return x.Type
	}
	return File_plain
}

func (x *File) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

type Field_SubField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Can be a string or number.
	Type *Field_Type `protobuf:"varint,1,opt,name=type,proto3,enum=skiff.registry.v1alpha1.Field_Type,oneof" json:"type,omitempty"`
	// Restrict your options to a set of values to choose.
	Enum          *structpb.ListValue `protobuf:"bytes,2,opt,name=enum,proto3,oneof" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field_SubField) Reset() {
	*x = Field_SubField{}
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field_SubField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field_SubField) ProtoMessage() {}

func (x *Field_SubField) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_registry_v1alpha1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field_SubField.ProtoReflect.Descriptor instead.
func (*Field_SubField) Descriptor() ([]byte, []int) {
	return file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Field_SubField) GetType() Field_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Field_string
}

func (x *Field_SubField) GetEnum() *structpb.ListValue {
	if x != nil {
		return x.Enum
	}
	return nil
}

var File_skiff_registry_v1alpha1_registry_proto protoreflect.FileDescriptor

const file_skiff_registry_v1alpha1_registry_proto_rawDesc = "" +
	"\n" +
	"&skiff/registry/v1alpha1/registry.proto\x12\x17skiff.registry.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x87\x01\n" +
	"\bRegistry\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12<\n" +
	"\bpackages\x18\x03 \x03(\v2 .skiff.registry.v1alpha1.PackageR\bpackages\"\xcf\x01\n" +
	"\aPackage\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x123\n" +
	"\x05files\x18\x03 \x03(\v2\x1d.skiff.registry.v1alpha1.FileR\x05files\x12<\n" +
	"\x06schema\x18\x04 \x01(\v2\x1f.skiff.registry.v1alpha1.SchemaH\x00R\x06schema\x88\x01\x01B\t\n" +
	"\a_schema\"\xa0\x01\n" +
	"\x06Schema\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.skiff.registry.v1alpha1.FieldR\x06fields:^\xbaH[\x1aY\n" +
	"\x12unique_field_names\x12\x1eall field names must be unique\x1a#this.fields.map(v, v.name).unique()\"\xa1\n" +
	"\n" +
	"\x05Field\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12D\n" +
	"\x04type\x18\x02 \x01(\x0e2#.skiff.registry.v1alpha1.Field.TypeB\x06\xbaH\x03\xc8\x01\x01H\x00R\x04type\x88\x01\x01\x12B\n" +
	"\x05items\x18\x03 \x01(\v2'.skiff.registry.v1alpha1.Field.SubFieldH\x01R\x05items\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x125\n" +
	"\adefault\x18\x05 \x01(\v2\x16.google.protobuf.ValueH\x03R\adefault\x88\x01\x01\x123\n" +
	"\x04enum\x18\x06 \x01(\v2\x1a.google.protobuf.ListValueH\x04R\x04enum\x88\x01\x01\x1a\xe9\x02\n" +
	"\bSubField\x12K\n" +
	"\x04type\x18\x01 \x01(\x0e2#.skiff.registry.v1alpha1.Field.TypeB\r\xbaH\n" +
	"\xc8\x01\x01\x82\x01\x04\x18\x00\x18\x02H\x00R\x04type\x88\x01\x01\x123\n" +
	"\x04enum\x18\x02 \x01(\v2\x1a.google.protobuf.ListValueH\x01R\x04enum\x88\x01\x01:\xc8\x01\xbaH\xc4\x01\x1a\xc1\x01\n" +
	"\x12enums_type_invalid\x12.enums only supported for type number or string\x1a{has(this.enum) ? this.type in [skiff.registry.v1alpha1.Field.Type.string, skiff.registry.v1alpha1.Field.Type.number] : trueB\a\n" +
	"\x05_typeB\a\n" +
	"\x05_enum\"3\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06string\x10\x00\x12\b\n" +
	"\x04bool\x10\x01\x12\n" +
	"\n" +
	"\x06number\x10\x02\x12\t\n" +
	"\x05array\x10\x03:\x84\x04\xbaH\x80\x04\x1a\xc2\x01\n" +
	"\x12enums_type_invalid\x12/enums only supported for type number, or string\x1a{has(this.enum) ? this.type in [skiff.registry.v1alpha1.Field.Type.string, skiff.registry.v1alpha1.Field.Type.number] : true\x1a\x94\x01\n" +
	"\x0eitems_required\x12\x19items required for arrays\x1agthis.type == skiff.registry.v1alpha1.Field.Type.array ? (has(this.items) && has(this.items.type)): true\x1a\xa1\x01\n" +
	"\x17default_must_be_in_enum\x129default value must be one of enum values when enum is set\x1aKhas(this.default) && size(this.enum) > 0 ? this.default in this.enum : trueB\a\n" +
	"\x05_typeB\b\n" +
	"\x06_itemsB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_defaultB\a\n" +
	"\x05_enum\"\xf3\x01\n" +
	"\x04File\x12\x1b\n" +
	"\x04path\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04path\x12\x1f\n" +
	"\x06target\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06target\x12\x15\n" +
	"\x03raw\x18\x03 \x01(\fH\x00R\x03raw\x88\x01\x01\x126\n" +
	"\x04type\x18\x04 \x01(\x0e2\".skiff.registry.v1alpha1.File.TypeR\x04type\x12\x1d\n" +
	"\acontent\x18\x05 \x01(\tH\x01R\acontent\x88\x01\x01\"+\n" +
	"\x04Type\x12\t\n" +
	"\x05plain\x10\x00\x12\f\n" +
	"\btemplate\x10\x01\x12\n" +
	"\n" +
	"\x06plugin\x10\x02B\x06\n" +
	"\x04_rawB\n" +
	"\n" +
	"\b_contentB\xe4\x01\n" +
	"\x1bcom.skiff.registry.v1alpha1B\rRegistryProtoP\x01Z8github.com/skiff-sh/skiff/api/go/skiff/registry/v1alpha1\xa2\x02\x03SRX\xaa\x02\x17Skiff.Registry.V1alpha1\xca\x02\x17Skiff\\Registry\\V1alpha1\xe2\x02#Skiff\\Registry\\V1alpha1\\GPBMetadata\xea\x02\x19Skiff::Registry::V1alpha1b\x06proto3"

var (
	file_skiff_registry_v1alpha1_registry_proto_rawDescOnce sync.Once
	file_skiff_registry_v1alpha1_registry_proto_rawDescData []byte
)

func file_skiff_registry_v1alpha1_registry_proto_rawDescGZIP() []byte {
	file_skiff_registry_v1alpha1_registry_proto_rawDescOnce.Do(func() {
		file_skiff_registry_v1alpha1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skiff_registry_v1alpha1_registry_proto_rawDesc), len(file_skiff_registry_v1alpha1_registry_proto_rawDesc)))
	})
	return file_skiff_registry_v1alpha1_registry_proto_rawDescData
}

var file_skiff_registry_v1alpha1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_skiff_registry_v1alpha1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_skiff_registry_v1alpha1_registry_proto_goTypes = []any{
	(Field_Type)(0),            // 0: skiff.registry.v1alpha1.Field.Type
	(File_Type)(0),             // 1: skiff.registry.v1alpha1.File.Type
	(*Registry)(nil),           // 2: skiff.registry.v1alpha1.Registry
	(*Package)(nil),            // 3: skiff.registry.v1alpha1.Package
	(*Schema)(nil),             // 4: skiff.registry.v1alpha1.Schema
	(*Field)(nil),              // 5: skiff.registry.v1alpha1.Field
	(*File)(nil),               // 6: skiff.registry.v1alpha1.File
	(*Field_SubField)(nil),     // 7: skiff.registry.v1alpha1.Field.SubField
	(*structpb.Value)(nil),     // 8: google.protobuf.Value
	(*structpb.ListValue)(nil), // 9: google.protobuf.ListValue
}
var file_skiff_registry_v1alpha1_registry_proto_depIdxs = []int32{
	3,  // 0: skiff.registry.v1alpha1.Registry.packages:type_name -> skiff.registry.v1alpha1.Package
	6,  // 1: skiff.registry.v1alpha1.Package.files:type_name -> skiff.registry.v1alpha1.File
	4,  // 2: skiff.registry.v1alpha1.Package.schema:type_name -> skiff.registry.v1alpha1.Schema
	5,  // 3: skiff.registry.v1alpha1.Schema.fields:type_name -> skiff.registry.v1alpha1.Field
	0,  // 4: skiff.registry.v1alpha1.Field.type:type_name -> skiff.registry.v1alpha1.Field.Type
	7,  // 5: skiff.registry.v1alpha1.Field.items:type_name -> skiff.registry.v1alpha1.Field.SubField
	8,  // 6: skiff.registry.v1alpha1.Field.default:type_name -> google.protobuf.Value
	9,  // 7: skiff.registry.v1alpha1.Field.enum:type_name -> google.protobuf.ListValue
	1,  // 8: skiff.registry.v1alpha1.File.type:type_name -> skiff.registry.v1alpha1.File.Type
	0,  // 9: skiff.registry.v1alpha1.Field.SubField.type:type_name -> skiff.registry.v1alpha1.Field.Type
	9,  // 10: skiff.registry.v1alpha1.Field.SubField.enum:type_name -> google.protobuf.ListValue
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_skiff_registry_v1alpha1_registry_proto_init() }
func file_skiff_registry_v1alpha1_registry_proto_init() {
	if File_skiff_registry_v1alpha1_registry_proto != nil {
		return
	}
	file_skiff_registry_v1alpha1_registry_proto_msgTypes[1].OneofWrappers = []any{}
	file_skiff_registry_v1alpha1_registry_proto_msgTypes[3].OneofWrappers = []any{}
	file_skiff_registry_v1alpha1_registry_proto_msgTypes[4].OneofWrappers = []any{}
	file_skiff_registry_v1alpha1_registry_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skiff_registry_v1alpha1_registry_proto_rawDesc), len(file_skiff_registry_v1alpha1_registry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skiff_registry_v1alpha1_registry_proto_goTypes,
		DependencyIndexes: file_skiff_registry_v1alpha1_registry_proto_depIdxs,
		EnumInfos:         file_skiff_registry_v1alpha1_registry_proto_enumTypes,
		MessageInfos:      file_skiff_registry_v1alpha1_registry_proto_msgTypes,
	}.Build()
	File_skiff_registry_v1alpha1_registry_proto = out.File
	file_skiff_registry_v1alpha1_registry_proto_goTypes = nil
	file_skiff_registry_v1alpha1_registry_proto_depIdxs = nil
}
