// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: skiff/plugin/v1alpha1/plugin.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source path of this plugin.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The intended target filepath to be edited/created by this plugin.
	Target        string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_skiff_plugin_v1alpha1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_plugin_v1alpha1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_skiff_plugin_v1alpha1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type WriteFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new contents of the file.
	Contents      []byte `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_skiff_plugin_v1alpha1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_plugin_v1alpha1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_skiff_plugin_v1alpha1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *WriteFileResponse) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_skiff_plugin_v1alpha1_plugin_proto protoreflect.FileDescriptor

const file_skiff_plugin_v1alpha1_plugin_proto_rawDesc = "" +
	"\n" +
	"\"skiff/plugin/v1alpha1/plugin.proto\x12\x15skiff.plugin.v1alpha1\">\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"/\n" +
	"\x11WriteFileResponse\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\fR\bcontentsB\xd6\x01\n" +
	"\x19com.skiff.plugin.v1alpha1B\vPluginProtoP\x01Z6github.com/skiff-sh/skiff/api/go/skiff/plugin/v1alpha1\xa2\x02\x03SPX\xaa\x02\x15Skiff.Plugin.V1alpha1\xca\x02\x15Skiff\\Plugin\\V1alpha1\xe2\x02!Skiff\\Plugin\\V1alpha1\\GPBMetadata\xea\x02\x17Skiff::Plugin::V1alpha1b\x06proto3"

var (
	file_skiff_plugin_v1alpha1_plugin_proto_rawDescOnce sync.Once
	file_skiff_plugin_v1alpha1_plugin_proto_rawDescData []byte
)

func file_skiff_plugin_v1alpha1_plugin_proto_rawDescGZIP() []byte {
	file_skiff_plugin_v1alpha1_plugin_proto_rawDescOnce.Do(func() {
		file_skiff_plugin_v1alpha1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skiff_plugin_v1alpha1_plugin_proto_rawDesc), len(file_skiff_plugin_v1alpha1_plugin_proto_rawDesc)))
	})
	return file_skiff_plugin_v1alpha1_plugin_proto_rawDescData
}

var file_skiff_plugin_v1alpha1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_skiff_plugin_v1alpha1_plugin_proto_goTypes = []any{
	(*WriteFileRequest)(nil),  // 0: skiff.plugin.v1alpha1.WriteFileRequest
	(*WriteFileResponse)(nil), // 1: skiff.plugin.v1alpha1.WriteFileResponse
}
var file_skiff_plugin_v1alpha1_plugin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skiff_plugin_v1alpha1_plugin_proto_init() }
func file_skiff_plugin_v1alpha1_plugin_proto_init() {
	if File_skiff_plugin_v1alpha1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skiff_plugin_v1alpha1_plugin_proto_rawDesc), len(file_skiff_plugin_v1alpha1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skiff_plugin_v1alpha1_plugin_proto_goTypes,
		DependencyIndexes: file_skiff_plugin_v1alpha1_plugin_proto_depIdxs,
		MessageInfos:      file_skiff_plugin_v1alpha1_plugin_proto_msgTypes,
	}.Build()
	File_skiff_plugin_v1alpha1_plugin_proto = out.File
	file_skiff_plugin_v1alpha1_plugin_proto_goTypes = nil
	file_skiff_plugin_v1alpha1_plugin_proto_depIdxs = nil
}
