// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: skiff/plugin/v1alpha1/plugin.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FileSpec with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileSpec) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileSpec with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileSpecMultiError, or nil
// if none found.
func (m *FileSpec) ValidateAll() error {
	return m.validate(true)
}

func (m *FileSpec) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Path

	// no validation rules for Content

	if len(errors) > 0 {
		return FileSpecMultiError(errors)
	}

	return nil
}

// FileSpecMultiError is an error wrapping multiple validation errors returned
// by FileSpec.ValidateAll() if the designated constraints aren't met.
type FileSpecMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileSpecMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileSpecMultiError) AllErrors() []error { return m }

// FileSpecValidationError is the validation error returned by
// FileSpec.Validate if the designated constraints aren't met.
type FileSpecValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileSpecValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileSpecValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileSpecValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileSpecValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileSpecValidationError) ErrorName() string { return "FileSpecValidationError" }

// Error satisfies the builtin error interface
func (e FileSpecValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileSpec.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileSpecValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileSpecValidationError{}

// Validate checks the field values on WriteFileRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WriteFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WriteFileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WriteFileRequestMultiError, or nil if none found.
func (m *WriteFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *WriteFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFile()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WriteFileRequestValidationError{
					field:  "File",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WriteFileRequestValidationError{
					field:  "File",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WriteFileRequestValidationError{
				field:  "File",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WriteFileRequestMultiError(errors)
	}

	return nil
}

// WriteFileRequestMultiError is an error wrapping multiple validation errors
// returned by WriteFileRequest.ValidateAll() if the designated constraints
// aren't met.
type WriteFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WriteFileRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WriteFileRequestMultiError) AllErrors() []error { return m }

// WriteFileRequestValidationError is the validation error returned by
// WriteFileRequest.Validate if the designated constraints aren't met.
type WriteFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WriteFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WriteFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WriteFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WriteFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WriteFileRequestValidationError) ErrorName() string { return "WriteFileRequestValidationError" }

// Error satisfies the builtin error interface
func (e WriteFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWriteFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WriteFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WriteFileRequestValidationError{}

// Validate checks the field values on WriteFileResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WriteFileResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WriteFileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WriteFileResponseMultiError, or nil if none found.
func (m *WriteFileResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *WriteFileResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Contents

	if len(errors) > 0 {
		return WriteFileResponseMultiError(errors)
	}

	return nil
}

// WriteFileResponseMultiError is an error wrapping multiple validation errors
// returned by WriteFileResponse.ValidateAll() if the designated constraints
// aren't met.
type WriteFileResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WriteFileResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WriteFileResponseMultiError) AllErrors() []error { return m }

// WriteFileResponseValidationError is the validation error returned by
// WriteFileResponse.Validate if the designated constraints aren't met.
type WriteFileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WriteFileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WriteFileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WriteFileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WriteFileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WriteFileResponseValidationError) ErrorName() string {
	return "WriteFileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e WriteFileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWriteFileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WriteFileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WriteFileResponseValidationError{}
