// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filesystemmocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewFilesystem creates a new instance of Filesystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilesystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *Filesystem {
	mock := &Filesystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Filesystem is an autogenerated mock type for the Filesystem type
type Filesystem struct {
	mock.Mock
}

type Filesystem_Expecter struct {
	mock *mock.Mock
}

func (_m *Filesystem) EXPECT() *Filesystem_Expecter {
	return &Filesystem_Expecter{mock: &_m.Mock}
}

// AsRel provides a mock function for the type Filesystem
func (_mock *Filesystem) AsRel(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for AsRel")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Filesystem_AsRel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsRel'
type Filesystem_AsRel_Call struct {
	*mock.Call
}

// AsRel is a helper method to define mock.On call
//   - name string
func (_e *Filesystem_Expecter) AsRel(name interface{}) *Filesystem_AsRel_Call {
	return &Filesystem_AsRel_Call{Call: _e.mock.On("AsRel", name)}
}

func (_c *Filesystem_AsRel_Call) Run(run func(name string)) *Filesystem_AsRel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Filesystem_AsRel_Call) Return(s string, err error) *Filesystem_AsRel_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Filesystem_AsRel_Call) RunAndReturn(run func(name string) (string, error)) *Filesystem_AsRel_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type Filesystem
func (_mock *Filesystem) Exists(name string) bool {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Filesystem_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type Filesystem_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - name string
func (_e *Filesystem_Expecter) Exists(name interface{}) *Filesystem_Exists_Call {
	return &Filesystem_Exists_Call{Call: _e.mock.On("Exists", name)}
}

func (_c *Filesystem_Exists_Call) Run(run func(name string)) *Filesystem_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Filesystem_Exists_Call) Return(b bool) *Filesystem_Exists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Filesystem_Exists_Call) RunAndReturn(run func(name string) bool) *Filesystem_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type Filesystem
func (_mock *Filesystem) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Filesystem_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type Filesystem_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *Filesystem_Expecter) Open(name interface{}) *Filesystem_Open_Call {
	return &Filesystem_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *Filesystem_Open_Call) Run(run func(name string)) *Filesystem_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Filesystem_Open_Call) Return(file fs.File, err error) *Filesystem_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *Filesystem_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *Filesystem_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type Filesystem
func (_mock *Filesystem) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Filesystem_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type Filesystem_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *Filesystem_Expecter) ReadFile(name interface{}) *Filesystem_ReadFile_Call {
	return &Filesystem_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *Filesystem_ReadFile_Call) Run(run func(name string)) *Filesystem_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Filesystem_ReadFile_Call) Return(bytes []byte, err error) *Filesystem_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Filesystem_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *Filesystem_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type Filesystem
func (_mock *Filesystem) WriteFile(name string, content []byte) error {
	ret := _mock.Called(name, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(name, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Filesystem_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type Filesystem_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - content []byte
func (_e *Filesystem_Expecter) WriteFile(name interface{}, content interface{}) *Filesystem_WriteFile_Call {
	return &Filesystem_WriteFile_Call{Call: _e.mock.On("WriteFile", name, content)}
}

func (_c *Filesystem_WriteFile_Call) Run(run func(name string, content []byte)) *Filesystem_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Filesystem_WriteFile_Call) Return(err error) *Filesystem_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Filesystem_WriteFile_Call) RunAndReturn(run func(name string, content []byte) error) *Filesystem_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
