// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filesystemmocks

import (
	"github.com/skiff-sh/skiff/pkg/filesystem"
	mock "github.com/stretchr/testify/mock"
)

// NewWriterTo creates a new instance of WriterTo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriterTo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriterTo {
	mock := &WriterTo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WriterTo is an autogenerated mock type for the WriterTo type
type WriterTo struct {
	mock.Mock
}

type WriterTo_Expecter struct {
	mock *mock.Mock
}

func (_m *WriterTo) EXPECT() *WriterTo_Expecter {
	return &WriterTo_Expecter{mock: &_m.Mock}
}

// WriteTo provides a mock function for the type WriterTo
func (_mock *WriterTo) WriteTo(fsys filesystem.Filesystem) error {
	ret := _mock.Called(fsys)

	if len(ret) == 0 {
		panic("no return value specified for WriteTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(filesystem.Filesystem) error); ok {
		r0 = returnFunc(fsys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriterTo_WriteTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTo'
type WriterTo_WriteTo_Call struct {
	*mock.Call
}

// WriteTo is a helper method to define mock.On call
//   - fsys filesystem.Filesystem
func (_e *WriterTo_Expecter) WriteTo(fsys interface{}) *WriterTo_WriteTo_Call {
	return &WriterTo_WriteTo_Call{Call: _e.mock.On("WriteTo", fsys)}
}

func (_c *WriterTo_WriteTo_Call) Run(run func(fsys filesystem.Filesystem)) *WriterTo_WriteTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filesystem.Filesystem
		if args[0] != nil {
			arg0 = args[0].(filesystem.Filesystem)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WriterTo_WriteTo_Call) Return(err error) *WriterTo_WriteTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriterTo_WriteTo_Call) RunAndReturn(run func(fsys filesystem.Filesystem) error) *WriterTo_WriteTo_Call {
	_c.Call.Return(run)
	return _c
}
